import {
    AppstoreOutlined,
    AuditOutlined,
    AimOutlined,
    ArrowLeftOutlined,
    ArrowRightOutlined,
    FolderOpenOutlined,
    DeleteOutlined,
    DownOutlined,
    DashboardOutlined,
    DragOutlined,
    FontSizeOutlined,
    GroupOutlined,
    LinkOutlined,
    LogoutOutlined,
    MoonOutlined,
    MenuOutlined,
    MenuFoldOutlined,
    MenuUnfoldOutlined,
    MinusOutlined,
    PictureOutlined,
    PauseOutlined,
    PlayCircleOutlined,
    PlusOutlined,
    ReloadOutlined,
    RedoOutlined,
    SearchOutlined,
    SelectOutlined,
    SettingOutlined,
    SunOutlined,
    TeamOutlined,
    UserOutlined,
    UndoOutlined,
    TransactionOutlined,
    FileTextOutlined,
} from "@ant-design/icons";
import type { CSSProperties } from "react";

const icons = {
    overview: DashboardOutlined,
    down: DownOutlined,
    credits: TransactionOutlined,
    logs: FileTextOutlined,
    budget: AuditOutlined,
    menu: MenuOutlined,
    panelOpen: MenuUnfoldOutlined,
    panelClose: MenuFoldOutlined,
    projects: FolderOpenOutlined,
    canvas: AppstoreOutlined,
    assets: PictureOutlined,
    pause: PauseOutlined,
    play: PlayCircleOutlined,
    back: ArrowLeftOutlined,
    enter: ArrowRightOutlined,
    logout: LogoutOutlined,
    moon: MoonOutlined,
    sun: SunOutlined,
    plus: PlusOutlined,
    reload: ReloadOutlined,
    search: SearchOutlined,
    settings: SettingOutlined,
    team: TeamOutlined,
    user: UserOutlined,
    text: FontSizeOutlined,
    group: GroupOutlined,
    select: SelectOutlined,
    pan: DragOutlined,
    link: LinkOutlined,
    delete: DeleteOutlined,
    undo: UndoOutlined,
    redo: RedoOutlined,
    fit: AimOutlined,
    minus: MinusOutlined,
};
export function ProjectIcon({ name, style }: { name: keyof typeof icons; style?: CSSProperties }) {
    const Icon = icons[name];
    return <Icon aria-hidden style={style} />;
}
